In [2]:
from RAG_model.evaluation.evaluation import main as evaluate

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [3]:
from RAG_model.evaluation.model_analysis import run_config
from RAG_model.ingestion.config import BASELINE_RUN_CONFIG

In [3]:
detailed_questions, summary = await evaluate(BASELINE_RUN_CONFIG, retrieval_only=True)

Starting to create the parquet file.
Start the Ingestion process.
SEC html ingestion Complete
Chunking step Complete
Embedding Step Complete
Starting to create the Qdrant database.
Created collection: sec_filings_openai_text-embedding-3-small_v2_3
Stored 100/9522 chunks
Stored 200/9522 chunks
Stored 300/9522 chunks
Stored 400/9522 chunks
Stored 500/9522 chunks
Stored 600/9522 chunks
Stored 700/9522 chunks
Stored 800/9522 chunks
Stored 900/9522 chunks
Stored 1000/9522 chunks
Stored 1100/9522 chunks
Stored 1200/9522 chunks
Stored 1300/9522 chunks
Stored 1400/9522 chunks
Stored 1500/9522 chunks
Stored 1600/9522 chunks
Stored 1700/9522 chunks
Stored 1800/9522 chunks
Stored 1900/9522 chunks
Stored 2000/9522 chunks
Stored 2100/9522 chunks
Stored 2200/9522 chunks
Stored 2300/9522 chunks
Stored 2400/9522 chunks
Stored 2500/9522 chunks
Stored 2600/9522 chunks
Stored 2700/9522 chunks
Stored 2800/9522 chunks
Stored 2900/9522 chunks
Stored 3000/9522 chunks
Stored 3100/9522 chunks
Stored 3200/9522 chunks
Stored 3300/9522 chunks
Stored 3400/9522 chunks
Stored 3500/9522 chunks
Stored 3600/9522 chunks
Stored 3700/9522 chunks
Stored 3800/9522 chunks
Stored 3900/9522 chunks
Stored 4000/9522 chunks
Stored 4100/9522 chunks
Stored 4200/9522 chunks
Stored 4300/9522 chunks
Stored 4400/9522 chunks
Stored 4500/9522 chunks
Stored 4600/9522 chunks
Stored 4700/9522 chunks
Stored 4800/9522 chunks
Stored 4900/9522 chunks
Stored 5000/9522 chunks
Stored 5100/9522 chunks
Stored 5200/9522 chunks
Stored 5300/9522 chunks
Stored 5400/9522 chunks
Stored 5500/9522 chunks
Stored 5600/9522 chunks
Stored 5700/9522 chunks
Stored 5800/9522 chunks
Stored 5900/9522 chunks
Stored 6000/9522 chunks
Stored 6100/9522 chunks
Stored 6200/9522 chunks
Stored 6300/9522 chunks
Stored 6400/9522 chunks
Stored 6500/9522 chunks
Stored 6600/9522 chunks
Stored 6700/9522 chunks
Stored 6800/9522 chunks
Stored 6900/9522 chunks
Stored 7000/9522 chunks
Stored 7100/9522 chunks
Stored 7200/9522 chunks
Stored 7300/9522 chunks
Stored 7400/9522 chunks
Stored 7500/9522 chunks
Stored 7600/9522 chunks
Stored 7700/9522 chunks
Stored 7800/9522 chunks
Stored 7900/9522 chunks
Stored 8000/9522 chunks
Stored 8100/9522 chunks
Stored 8200/9522 chunks
Stored 8300/9522 chunks
Stored 8400/9522 chunks
Stored 8500/9522 chunks
Stored 8600/9522 chunks
Stored 8700/9522 chunks
Stored 8800/9522 chunks
Stored 8900/9522 chunks
Stored 9000/9522 chunks
Stored 9100/9522 chunks
Stored 9200/9522 chunks
Stored 9300/9522 chunks
Stored 9400/9522 chunks
Stored 9500/9522 chunks
Stored 9522/9522 chunks
Ingestion completed: {'filings': 76, 'chunks': 9522, 'embedding_model': 'openai/text-embedding-3-small', 'embedding_dimensions': 1536}
Questions [openai/gpt-5.6-luna]:   0%|                                       | 0/40 [00:00<?, ?it/s] | Evaluating Q1: According to FETH's 2024 annual filing, what is the Sponsor Fee rate, what as...
Questions [openai/gpt-5.6-luna]:   2%|7                              | 1/40 [00:07<05:11,  7.99s/it] | Evaluating Q2: According to FBTC's 2024 annual filing, what is the Sponsor Fee rate, what as...
Questions [openai/gpt-5.6-luna]:   5%|#5                             | 2/40 [00:15<04:53,  7.71s/it] | Evaluating Q3: Describe ETHA's 2024 launch using the seeding date, number and price of seed ...
Questions [openai/gpt-5.6-luna]:   8%|##3                            | 3/40 [00:22<04:41,  7.61s/it] | Evaluating Q4: In IBIT's Q1 2025 filing, where do the shares trade, which benchmark is used ...
Questions [openai/gpt-5.6-luna]:  10%|###1                           | 4/40 [00:30<04:32,  7.56s/it] | Evaluating Q5: What investment objective does GBTC describe in its 2024 annual filing, where...
Questions [openai/gpt-5.6-luna]:  12%|###8                           | 5/40 [00:37<04:22,  7.49s/it] | Evaluating Q6: What commencement date, ticker, and registered exchange are reported for Fide...
Questions [openai/gpt-5.6-luna]:  15%|####6                          | 6/40 [00:44<04:11,  7.41s/it] | Evaluating Q7: When did FBTC commence operations, how many shares form a Basket, and what de...
Questions [openai/gpt-5.6-luna]:  18%|#####4                         | 7/40 [00:51<04:02,  7.35s/it] | Evaluating Q8: Which firms had agreed to act as Authorized Participants for ETHE as of its 2...
Questions [openai/gpt-5.6-luna]:  20%|######2                        | 8/40 [00:58<03:54,  7.33s/it] | Evaluating Q9: Explain the daily-to-monthly process by which FETH's Sponsor Fee is calculate...
Questions [openai/gpt-5.6-luna]:  22%|######9                        | 9/40 [01:06<03:49,  7.39s/it] | Evaluating Q10: Explain the daily-to-monthly process by which FBTC's Sponsor Fee is calculate...
Questions [openai/gpt-5.6-luna]:  25%|#######5                      | 10/40 [01:13<03:40,  7.35s/it] | Evaluating Q11: How does IBIT determine NAV on a Business Day, from valuing bitcoin through c...
Questions [openai/gpt-5.6-luna]:  28%|########2                     | 11/40 [01:20<03:31,  7.30s/it] | Evaluating Q12: How did ETHA move from seed investment to active operations in 2024?
Questions [openai/gpt-5.6-luna]:  30%|#########                     | 12/40 [01:27<03:24,  7.30s/it] | Evaluating Q13: What must a party do to become an Authorized Participant for FETH, and how co...
Questions [openai/gpt-5.6-luna]:  32%|#########7                    | 13/40 [01:33<03:14,  7.21s/it] | Evaluating Q14: How does FBTC issue or redeem shares, and how is a Basket tied to the Trust's...
Questions [openai/gpt-5.6-luna]:  35%|##########5                   | 14/40 [01:40<03:06,  7.16s/it] | Evaluating Q15: How is GBTC designed to provide Bitcoin exposure, and what deductions prevent...
Questions [openai/gpt-5.6-luna]:  38%|###########2                  | 15/40 [01:46<02:58,  7.13s/it] | Evaluating Q16: How does ETHA's Sponsor Fee accrue and how may it be paid according to the 20...
Questions [openai/gpt-5.6-luna]:  40%|############                  | 16/40 [01:53<02:49,  7.07s/it] | Evaluating Q17: Compare FETH and FBTC Sponsor Fees by rate, calculation base, accrual asset, ...
Questions [openai/gpt-5.6-luna]:  42%|############7                 | 17/40 [01:59<02:41,  7.00s/it] | Evaluating Q18: Compare ETHA and FETH Sponsor Fee mechanics, including rate, calculation base...
Questions [openai/gpt-5.6-luna]:  45%|#############5                | 18/40 [02:05<02:32,  6.95s/it] | Evaluating Q19: Compare IBIT and GBTC by trading venue and stated approach to Bitcoin exposure.
Questions [openai/gpt-5.6-luna]:  48%|##############2               | 19/40 [02:11<02:25,  6.93s/it] | Evaluating Q20: Compare ETHA and ETHE by underlying crypto asset and listing exchange.
Questions [openai/gpt-5.6-luna]:  50%|###############               | 20/40 [02:18<02:18,  6.91s/it] | Evaluating Q21: Compare FBTC and FETH by commencement date, underlying asset, and Sponsor Fee...
Questions [openai/gpt-5.6-luna]:  52%|###############7              | 21/40 [02:24<02:10,  6.89s/it] | Evaluating Q22: Which began operations first, ETHA or FETH, by how many days, and on which ex...
Questions [openai/gpt-5.6-luna]:  55%|################5             | 22/40 [02:31<02:03,  6.87s/it] | Evaluating Q23: Compare GBTC and ETHE by underlying crypto asset, ticker, and listing exchange.
Questions [openai/gpt-5.6-luna]:  57%|#################2            | 23/40 [02:37<01:56,  6.83s/it] | Evaluating Q24: How do BlackRock's ETHA and Fidelity's FETH differ in launch date, trading ve...
Questions [openai/gpt-5.6-luna]:  60%|##################            | 24/40 [02:43<01:49,  6.82s/it] | Evaluating Q25: Create a concise operational profile of FETH covering launch date, venue, und...
Questions [openai/gpt-5.6-luna]:  62%|##################7           | 25/40 [02:50<01:42,  6.81s/it] | Evaluating Q26: Create a concise operational profile of FBTC covering launch date, Basket str...
Questions [openai/gpt-5.6-luna]:  65%|###################5          | 26/40 [02:57<01:35,  6.85s/it] | Evaluating Q27: Summarize ETHA's 2024 launch and explain how its seed transaction connects to...
Questions [openai/gpt-5.6-luna]:  68%|####################2         | 27/40 [03:04<01:28,  6.83s/it] | Evaluating Q28: Summarize how IBIT converts its Bitcoin holdings into a daily NAV per Share a...
Questions [openai/gpt-5.6-luna]:  70%|#####################         | 28/40 [03:10<01:21,  6.81s/it] | Evaluating Q29: Summarize GBTC's investment objective and explain why shareholder returns may...
Questions [openai/gpt-5.6-luna]:  72%|#####################7        | 29/40 [03:17<01:14,  6.79s/it] | Evaluating Q30: Summarize the main investor-facing differences between GBTC and ETHE using un...
Questions [openai/gpt-5.6-luna]:  75%|######################5       | 30/40 [03:23<01:07,  6.79s/it] | Evaluating Q31: Summarize the main operational similarities and differences between Fidelity'...
Questions [openai/gpt-5.6-luna]:  78%|#######################2      | 31/40 [03:30<01:01,  6.79s/it] | Evaluating Q32: Summarize the main operational differences between BlackRock's ETHA and Fidel...
Questions [openai/gpt-5.6-luna]:  80%|########################      | 32/40 [03:39<00:54,  6.86s/it] | Evaluating Q33: What was FBTC's balance sheet for Q2 2028?
Questions [openai/gpt-5.6-luna]:  82%|########################7     | 33/40 [03:45<00:47,  6.83s/it] | Evaluating Q34: Provide the 2025 financial statements for ticker COIN.
Questions [openai/gpt-5.6-luna]:  85%|#########################5    | 34/40 [03:52<00:40,  6.82s/it] | Evaluating Q35: Before 2016, did any fund in the corpus report a negative cash balance?
Questions [openai/gpt-5.6-luna]:  88%|##########################2   | 35/40 [03:59<00:34,  6.84s/it] | Evaluating Q36: Provide BlackRock's Solana ETF Sponsor Fee and 2025 financial statements.
Questions [openai/gpt-5.6-luna]:  90%|###########################   | 36/40 [04:07<00:27,  6.87s/it] | Evaluating Q37: How did FETH's risk factors change between its 2023 and 2025 annual filings?
Questions [openai/gpt-5.6-luna]:  92%|###########################7  | 37/40 [04:15<00:20,  6.90s/it] | Evaluating Q38: Based on the filings, what will Bitcoin's price be next month?
Questions [openai/gpt-5.6-luna]:  95%|############################5 | 38/40 [04:23<00:13,  6.92s/it] | Evaluating Q39: What Sponsor Fee does the XRP ETF in this corpus charge?
Questions [openai/gpt-5.6-luna]:  98%|#############################2| 39/40 [04:30<00:06,  6.95s/it] | Evaluating Q40: Compare ETHA's 2020 and 2024 balance sheets.
Questions [openai/gpt-5.6-luna]: 100%|##############################| 40/40 [04:38<00:00,  6.97s/it] | Complete

In [4]:
summary

,scope,total_questions,answerable_questions,unanswerable_questions,correct_answers,overall_answer_accuracy,document_hit_rate_at_k,mean_document_recall_at_k,mrr,answerable_correct_answers,answerable_answer_accuracy,citation_validity_rate,mean_ragas_faithfulness,mean_ragas_factual_correctness,mean_ragas_context_precision,abstention_accuracy,mean_total_latency_ms,p95_total_latency_ms,mean_rag_total_tokens,total_rag_tokens
0,All questions,40,32,8,0,None,0.718750,0.843750,0.368893,0,None,None,None,None,None,None,6969.035208,7995.66955,22.600000,904
1,Hard,21,18,3,0,None,0.666667,0.805556,0.279619,0,None,None,None,None,None,None,6912.387400,7839.98700,22.619048,475
2,Medium,19,14,5,0,None,0.785714,0.892857,0.483673,0,None,None,None,None,None,None,7031.645942,8004.94880,22.578947,429

In [4]:
detailed_questions, summary = await evaluate(BASELINE_RUN_CONFIG, retrieval_only=True)

Parquet file already exists.
Collection already created.
Questions [openai/gpt-5.6-luna]:   0%|                                       | 0/40 [00:00<?, ?it/s] | Evaluating Q1: According to FETH's 2024 annual filing, what is the Sponsor Fee rate, what as...
Questions [openai/gpt-5.6-luna]:   2%|7                              | 1/40 [00:12<07:48, 12.02s/it] | Evaluating Q2: According to FBTC's 2024 annual filing, what is the Sponsor Fee rate, what as...
Questions [openai/gpt-5.6-luna]:   5%|#5                             | 2/40 [00:22<07:08, 11.29s/it] | Evaluating Q3: Describe ETHA's 2024 launch using the seeding date, number and price of seed ...
Questions [openai/gpt-5.6-luna]:   8%|##3                            | 3/40 [00:33<06:54, 11.19s/it] | Evaluating Q4: In IBIT's Q1 2025 filing, where do the shares trade, which benchmark is used ...
Questions [openai/gpt-5.6-luna]:  10%|###1                           | 4/40 [00:45<06:46, 11.29s/it] | Evaluating Q5: What investment objective does GBTC describe in its 2024 annual filing, where...
Questions [openai/gpt-5.6-luna]:  12%|###8                           | 5/40 [00:56<06:35, 11.29s/it] | Evaluating Q6: What commencement date, ticker, and registered exchange are reported for Fide...
Questions [openai/gpt-5.6-luna]:  15%|####6                          | 6/40 [01:06<06:16, 11.07s/it] | Evaluating Q7: When did FBTC commence operations, how many shares form a Basket, and what de...
Questions [openai/gpt-5.6-luna]:  18%|#####4                         | 7/40 [01:17<06:04, 11.04s/it] | Evaluating Q8: Which firms had agreed to act as Authorized Participants for ETHE as of its 2...
Questions [openai/gpt-5.6-luna]:  20%|######2                        | 8/40 [01:28<05:52, 11.01s/it] | Evaluating Q9: Explain the daily-to-monthly process by which FETH's Sponsor Fee is calculate...
Questions [openai/gpt-5.6-luna]:  22%|######9                        | 9/40 [01:37<05:36, 10.85s/it] | Evaluating Q10: Explain the daily-to-monthly process by which FBTC's Sponsor Fee is calculate...
Questions [openai/gpt-5.6-luna]:  25%|#######5                      | 10/40 [01:47<05:21, 10.71s/it] | Evaluating Q11: How does IBIT determine NAV on a Business Day, from valuing bitcoin through c...
Questions [openai/gpt-5.6-luna]:  28%|########2                     | 11/40 [01:57<05:10, 10.72s/it] | Evaluating Q12: How did ETHA move from seed investment to active operations in 2024?
Questions [openai/gpt-5.6-luna]:  30%|#########                     | 12/40 [02:08<04:58, 10.68s/it] | Evaluating Q13: What must a party do to become an Authorized Participant for FETH, and how co...
Questions [openai/gpt-5.6-luna]:  32%|#########7                    | 13/40 [02:19<04:49, 10.73s/it] | Evaluating Q14: How does FBTC issue or redeem shares, and how is a Basket tied to the Trust's...
Questions [openai/gpt-5.6-luna]:  35%|##########5                   | 14/40 [02:30<04:38, 10.73s/it] | Evaluating Q15: How is GBTC designed to provide Bitcoin exposure, and what deductions prevent...
Questions [openai/gpt-5.6-luna]:  38%|###########2                  | 15/40 [02:41<04:28, 10.75s/it] | Evaluating Q16: How does ETHA's Sponsor Fee accrue and how may it be paid according to the 20...
Questions [openai/gpt-5.6-luna]:  40%|############                  | 16/40 [02:51<04:17, 10.74s/it] | Evaluating Q17: Compare FETH and FBTC Sponsor Fees by rate, calculation base, accrual asset, ...
Questions [openai/gpt-5.6-luna]:  42%|############7                 | 17/40 [03:01<04:05, 10.69s/it] | Evaluating Q18: Compare ETHA and FETH Sponsor Fee mechanics, including rate, calculation base...
Questions [openai/gpt-5.6-luna]:  45%|#############5                | 18/40 [03:12<03:55, 10.71s/it] | Evaluating Q19: Compare IBIT and GBTC by trading venue and stated approach to Bitcoin exposure.
Questions [openai/gpt-5.6-luna]:  48%|##############2               | 19/40 [03:23<03:45, 10.73s/it] | Evaluating Q20: Compare ETHA and ETHE by underlying crypto asset and listing exchange.
Questions [openai/gpt-5.6-luna]:  50%|###############               | 20/40 [03:34<03:34, 10.74s/it] | Evaluating Q21: Compare FBTC and FETH by commencement date, underlying asset, and Sponsor Fee...
Questions [openai/gpt-5.6-luna]:  52%|###############7              | 21/40 [03:51<03:29, 11.02s/it] | Evaluating Q22: Which began operations first, ETHA or FETH, by how many days, and on which ex...
Questions [openai/gpt-5.6-luna]:  55%|################5             | 22/40 [04:02<03:18, 11.03s/it] | Evaluating Q23: Compare GBTC and ETHE by underlying crypto asset, ticker, and listing exchange.
Questions [openai/gpt-5.6-luna]:  57%|#################2            | 23/40 [04:13<03:07, 11.02s/it] | Evaluating Q24: How do BlackRock's ETHA and Fidelity's FETH differ in launch date, trading ve...
Questions [openai/gpt-5.6-luna]:  60%|##################            | 24/40 [04:24<02:56, 11.04s/it] | Evaluating Q25: Create a concise operational profile of FETH covering launch date, venue, und...
Questions [openai/gpt-5.6-luna]:  62%|##################7           | 25/40 [04:36<02:46, 11.07s/it] | Evaluating Q26: Create a concise operational profile of FBTC covering launch date, Basket str...
Questions [openai/gpt-5.6-luna]:  65%|###################5          | 26/40 [04:48<02:35, 11.09s/it] | Evaluating Q27: Summarize ETHA's 2024 launch and explain how its seed transaction connects to...
Questions [openai/gpt-5.6-luna]:  68%|####################2         | 27/40 [04:59<02:24, 11.09s/it] | Evaluating Q28: Summarize how IBIT converts its Bitcoin holdings into a daily NAV per Share a...
Questions [openai/gpt-5.6-luna]:  70%|#####################         | 28/40 [05:09<02:12, 11.06s/it] | Evaluating Q29: Summarize GBTC's investment objective and explain why shareholder returns may...
Questions [openai/gpt-5.6-luna]:  72%|#####################7        | 29/40 [05:20<02:01, 11.06s/it] | Evaluating Q30: Summarize the main investor-facing differences between GBTC and ETHE using un...
Questions [openai/gpt-5.6-luna]:  75%|######################5       | 30/40 [05:31<01:50, 11.06s/it] | Evaluating Q31: Summarize the main operational similarities and differences between Fidelity'...
Questions [openai/gpt-5.6-luna]:  78%|#######################2      | 31/40 [05:41<01:39, 11.02s/it] | Evaluating Q32: Summarize the main operational differences between BlackRock's ETHA and Fidel...
Questions [openai/gpt-5.6-luna]:  80%|########################      | 32/40 [05:51<01:27, 10.99s/it] | Evaluating Q33: What was FBTC's balance sheet for Q2 2028?
Questions [openai/gpt-5.6-luna]:  82%|########################7     | 33/40 [05:59<01:16, 10.89s/it] | Evaluating Q34: Provide the 2025 financial statements for ticker COIN.
Questions [openai/gpt-5.6-luna]:  85%|#########################5    | 34/40 [06:09<01:05, 10.86s/it] | Evaluating Q35: Before 2016, did any fund in the corpus report a negative cash balance?
Questions [openai/gpt-5.6-luna]:  88%|##########################2   | 35/40 [06:19<00:54, 10.85s/it] | Evaluating Q36: Provide BlackRock's Solana ETF Sponsor Fee and 2025 financial statements.
Questions [openai/gpt-5.6-luna]:  90%|###########################   | 36/40 [06:30<00:43, 10.84s/it] | Evaluating Q37: How did FETH's risk factors change between its 2023 and 2025 annual filings?
Questions [openai/gpt-5.6-luna]:  92%|###########################7  | 37/40 [06:39<00:32, 10.80s/it] | Evaluating Q38: Based on the filings, what will Bitcoin's price be next month?
Questions [openai/gpt-5.6-luna]:  95%|############################5 | 38/40 [06:49<00:21, 10.78s/it] | Evaluating Q39: What Sponsor Fee does the XRP ETF in this corpus charge?
Questions [openai/gpt-5.6-luna]:  98%|#############################2| 39/40 [06:59<00:10, 10.76s/it] | Evaluating Q40: Compare ETHA's 2020 and 2024 balance sheets.
Questions [openai/gpt-5.6-luna]: 100%|##############################| 40/40 [07:08<00:00, 10.72s/it] | Complete

In [5]:
summary

,scope,total_questions,answerable_questions,unanswerable_questions,correct_answers,overall_answer_accuracy,document_hit_rate_at_k,mean_document_recall_at_k,mrr,answerable_correct_answers,answerable_answer_accuracy,citation_validity_rate,mean_ragas_faithfulness,mean_ragas_factual_correctness,mean_ragas_context_precision,abstention_accuracy,mean_total_latency_ms,p95_total_latency_ms,mean_rag_total_tokens,total_rag_tokens
0,All questions,40,32,8,0,None,0.781250,0.812500,0.293249,0,None,None,None,None,None,None,10723.506003,11839.91156,22.600000,904
1,Hard,21,18,3,0,None,0.666667,0.722222,0.201532,0,None,None,None,None,None,None,10989.515614,11830.30910,22.619048,475
2,Medium,19,14,5,0,None,0.928571,0.928571,0.411170,0,None,None,None,None,None,None,10429.495379,11630.44349,22.578947,429